[project]
name = "cosm-c360-tools"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "psutil>=6.1.0",
    "questionary>=2.0.1",
    "tqdm>=4.67.1",
]
